apiVersion: v1
kind: ConfigMap
metadata:
{{- if .Values.service.name }}
  name: {{ .Values.service.name }}
{{- else }}
  name: {{ template "fullname" . }}
{{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  application.yml: |-
    server:
      applicationConnectors:
      - type: http
        port: {{ .Values.service.appPort }}
      adminConnectors:
      - type: http
        port: {{ .Values.service.adminPort }}
